n=int(input('Digite o número para a tabuada: '))
#print(n,'X 01 =',(n*1))
#print(n,'X 02 =',(n*2))
#print(n,'X 03 =',(n*3))
#print(n,'X 04 =',(n*4))
#print(n,'X 05 =',(n*5))
#print(n,'X 06 =',(n*6))
#print(n,'X 07 =',(n*7))
#print(n,'X 08 =',(n*8))
#print(n,'X 09 =',(n*9))
#print(n,'X 10 =',(n*10))
print('-'*12)
print('{} X {:>2} = {}'.format(n,1,(n*1)))
print('{} X {:>2} = {}'.format(n,2,(n*2)))
print('{} X {:>2} = {}'.format(n,3,(n*3)))
print('{} X {:>2} = {}'.format(n,4,(n*4)))
print('{} X {:>2} = {}'.format(n,5,(n*5)))
print('{} X {:>2} = {}'.format(n,6,(n*6)))
print('{} X {:>2} = {}'.format(n,7,(n*7)))
print('{} X {:>2} = {}'.format(n,8,(n*8)))
print('{} X {:>2} = {}'.format(n,9,(n*9)))
print('{} X {:>2} = {}'.format(n,10,(n*10)))
print('-'*12)
